// Row shapes for every Dexie table. See 00-PLAN.md §4.

export type Status = 'wishlist' | 'transit' | 'visited' | 'lived'
export type EntryKind = 'country' | 'subdivision' | 'city'
export type CitySource = 'bundled' | 'online'
export type UploadState = 'pending' | 'uploaded' | 'error'
export type StatMode = 'countries' | 'area' | 'population'
export type CountryDenominator = 'all' | 'unMember'
export type Theme = 'dark' | 'light'

// --- Reference tables (generated by the geo pipeline, replaceable) ---

export interface Country {
  code: string // ISO 3166-1 alpha-2, primary key
  code3: string
  name: string
  unMember: boolean
  territoryOf: string | null
  continent: string
  region: string
  areaKm2: number
  population: number
  capital: string | null
  lat: number
  lon: number
}

export interface Subdivision {
  id: string // `${countryCode}.${geonamesAdmin1}`
  countryCode: string
  name: string
  type: string
  geonamesAdmin1: string
  iso3166_2: string | null
  lat: number
  lon: number
}

export interface City {
  geonameId: number // primary key
  name: string
  asciiName: string
  countryCode: string
  subdivisionId: string | null // null for cities in countries with no admin-1 data (§02 acceptance)
  lat: number
  lon: number
  population: number
  source: CitySource
  searchTokens: string[]
}

// --- User tables (precious, synced) ---

export interface SyncedRecord {
  id: string
  createdAt: number
  updatedAt: number
  deletedAt: number | null
}

export interface Entry extends SyncedRecord {
  kind: EntryKind
  refId: string // countries.code | subdivisions.id | String(cities.geonameId)
  status: Status
  explicit: boolean
  firstVisited: string | null
  lastVisited: string | null
  notes: string
}

export interface Trip extends SyncedRecord {
  name: string
  startDate: string | null
  endDate: string | null
  isActive: boolean
  notes: string
  coverPhotoId: string | null
}

export interface TripEntry extends SyncedRecord {
  tripId: string
  entryId: string
  addedAt: number
}

export interface Photo extends SyncedRecord {
  entryId: string | null
  tripId: string | null
  caption: string
  takenAt: number | null
  lat: number | null
  lon: number | null
  width: number
  height: number
  bytes: number
  driveFileId: string | null
  uploadState: UploadState
}

// Binary blobs, device-only — never serialised into the sync JSON.
export interface PhotoBlob {
  photoId: string
  full: Blob
  thumb: Blob
}

export interface Settings {
  id: 1
  statMode: StatMode
  countryDenominator: CountryDenominator
  theme: Theme
  autoSync: boolean
  lastSyncAt: number | null
  deviceId: string
  // Device-local reference-data marker: which geo build has been seeded into
  // this device's IndexedDB. NOT a user preference — Phase 7 sync must not
  // overwrite it from a remote (like deviceId, it is per-device). 0 = unseeded.
  geoDataVersion: number
}

export interface SyncState {
  id: 1
  revision: number
  remoteRevision: number
  lastPulledAt: number | null
  lastPushedAt: number | null
}
