// Row shapes for every Dexie table. See 00-PLAN.md §4.

export type Status = 'wishlist' | 'transit' | 'visited' | 'lived'
export type EntryKind = 'country' | 'subdivision' | 'city'
export type CitySource = 'bundled' | 'online' | 'manual'
export type UploadState = 'pending' | 'uploaded' | 'error'
export type StatMode = 'countries' | 'area' | 'population'
export type CountryDenominator = 'all' | 'unMember'
export type Theme = 'dark' | 'light'

// --- Reference tables (generated by the geo pipeline, replaceable) ---

export interface Country {
  code: string // ISO 3166-1 alpha-2, primary key
  code3: string
  name: string
  unMember: boolean
  territoryOf: string | null
  continent: string
  region: string
  areaKm2: number
  population: number
  capital: string | null
  lat: number
  lon: number
}

export interface Subdivision {
  id: string // `${countryCode}.${geonamesAdmin1}`
  countryCode: string
  name: string
  type: string
  geonamesAdmin1: string
  iso3166_2: string | null
  lat: number
  lon: number
}

export interface City {
  // Positive = a real GeoNames id (bundled). Negative = synthesised locally for
  // an 'online' (Photon) or 'manual' city — see @/geo/cityWrites. The two
  // ranges can never collide, which is what makes a reference-data reseed safe
  // to preserve non-bundled rows across (@/geo/loader ensureReferenceData).
  geonameId: number // primary key
  name: string
  asciiName: string
  countryCode: string
  subdivisionId: string | null // null for cities in countries with no admin-1 data (§02 acceptance)
  lat: number | null // null when a manual place was added with no coordinates
  lon: number | null
  population: number
  source: CitySource
  searchTokens: string[]
}

// --- User tables (precious, synced) ---

export interface SyncedRecord {
  id: string
  createdAt: number
  updatedAt: number
  deletedAt: number | null
}

export interface Entry extends SyncedRecord {
  kind: EntryKind
  refId: string // countries.code | subdivisions.id | String(cities.geonameId)
  // The *effective* status — what the map paints. For a derived entry that is
  // the highest status among its children; for an explicit one it is the higher
  // of the user's own choice and its children (00-PLAN.md §5.3).
  status: Status
  explicit: boolean // the user set this place's status directly
  // The user's own choice, kept alongside `status` so a country explicitly set
  // to `visited` can show as `lived` while a lived city sits inside it and drop
  // back to `visited` when that city is downgraded — one field cannot hold both.
  // Invariant, maintained by @/domain/cascade: `explicit === (explicitStatus !== null)`.
  // Not indexed, so adding it needed no Dexie version bump. (Addition to plan §4.)
  explicitStatus: Status | null
  firstVisited: string | null
  lastVisited: string | null
  notes: string
}

export interface Trip extends SyncedRecord {
  name: string
  startDate: string | null
  endDate: string | null
  isActive: boolean
  notes: string
  coverPhotoId: string | null
}

export interface TripEntry extends SyncedRecord {
  tripId: string
  entryId: string
  addedAt: number
}

export interface Photo extends SyncedRecord {
  entryId: string | null
  tripId: string | null
  caption: string
  takenAt: number | null
  lat: number | null
  lon: number | null
  width: number
  height: number
  bytes: number
  driveFileId: string | null
  uploadState: UploadState
}

// Binary blobs, device-only — never serialised into the sync JSON.
export interface PhotoBlob {
  photoId: string
  full: Blob
  thumb: Blob
}

export interface Settings {
  id: 1
  // --- synced (see @/sync/types SyncableSettings) ---
  statMode: StatMode
  countryDenominator: CountryDenominator
  theme: Theme
  // --- device-local, never overwritten from a remote ---
  autoSync: boolean
  lastSyncAt: number | null
  deviceId: string
  // Device-local reference-data marker: which geo build has been seeded into
  // this device's IndexedDB. NOT a user preference — Phase 7 sync must not
  // overwrite it from a remote (like deviceId, it is per-device). 0 = unseeded.
  geoDataVersion: number
  // The user has connected Google Drive on THIS device. Persisted so app start
  // can silently re-acquire a token (tokens themselves are memory-only) instead
  // of popping consent every launch. Cleared on sign-out.
  driveConnected: boolean
  // Upload photo binaries over a cellular connection. Default false = Wi-Fi
  // only, so a photo-library import over a foreign SIM can't happen by accident
  // (07-sync-and-deploy.md task 5). Per-device network policy, not synced.
  photoUploadOnCellular: boolean
}

export interface SyncState {
  id: 1
  revision: number // local authored-change counter; bumped by every repo write
  remoteRevision: number // the `revision` of the Drive doc we last pulled/pushed
  lastPulledAt: number | null
  lastPushedAt: number | null
  // The `revision` value as of our last successful push. revision > pushedRevision
  // ⇒ there are local authored changes Drive has not seen yet (07 task 4).
  pushedRevision: number
  // The synced-settings object as of the last sync — the baseline for the
  // field-by-field three-way settings merge (@/sync/merge mergeSettings).
  lastSyncedSettings: {
    statMode: StatMode
    countryDenominator: CountryDenominator
    theme: Theme
  } | null
}
